# Generated by Django 5.0.6 on 2024-05-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepratmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('finance', 'finance'), ('sales', 'sales'), ('testing', 'testing'), ('devleopment', 'devleopment')], max_length=255)),
                ('user', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(max_length=500)),
                ('task_name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.depratmentuser')),
            ],
        ),
    ]
